version: '3.8'
services:
  mysql-identity:
    image: mysql:8
    environment:
      MYSQL_DATABASE: identity_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'

  postgres-employe:
    image: postgres:15
    environment:
      POSTGRES_DB: employe_db
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'

  mysql-beneficiaire:
    image: mysql:8
    environment:
      MYSQL_DATABASE: beneficiaire_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
