spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_db?createDatabaseIfNotExist=true
    username: root
    password: 

  jpa:
    hibernate:
      ddl-auto: update     # Changed from create-drop to update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Updated to MySQL8Dialect

server:
  port: 8081  # Changed from 8080 to 8081
